### ISSUE TITLE
Provide a way to filter

### ISSUE THREAD

**Issue by geekpete** [phocks/abc-stumble#1]
Hey Phocks!

Cool stumble tool.

Wondering if you could add a way to configure filters for it or at least see what categories it's dipping into?
For example, how do I filter out any news story about death and car accidents or maybe I could filter out all sport lol.

**Comment by phocks** [comment]
Yeah I thought about this yesterday. Definitely possible I reckon. Pull requests welcome haha

**Comment by phocks** [comment]
We seem to have category information, so we could use that to filter 

```
<category>Autism Spectrum Disorder</category>
            <category>Community and Society</category>
            <category>Disabilities</category>
            <category>Health</category>
            <category>Sport</category>
```

https://newsy.glitch.me/api/rss
